### ISSUE TITLE
transfer video error:  flow...: integer argument expected, got float

### ISSUE THREAD

**Issue by linrio** [6o6o/chainer-fast-neuralstyle#6]
Linux version : _Linux subuntu 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux_
GPU version:  _NVIDIA Corporation Device [10de:10f0] (rev a1)_

In Video Processing, after transform my videos to _.png_ images
I got the following error:
```
$ python generate.py 'frames/*.png' -m models/seurat.model -o dir/prefix_ -flow 0.02
frames/VID_20170413_212021_1.png 18.1061830521 sec
Calculating flow
Traceback (most recent call last):
  File "generate.py", line 57, in <module>
    flow = cv2.calcOpticalFlowFarneback(img1, img2, 0.5, 3, 15, 3, 5, 1.2, 0)
TypeError: integer argument expected, got float

```

What's wrong?

**Comment by 6o6o** [comment]
What is your OpenCV version? Check with
```
pip list
```
and search for opencv-python

**Comment by 6o6o** [comment]
What is your OpenCV version? Check with
```
pip show opencv-python
```

**Comment by linrio** [comment]
@6o6o 
```
$ pip show opencv-python
Name: opencv-python
Version: 3.2.0.7
Summary: Wrapper package for OpenCV python bindings.
Home-page: https://github.com/skvark/opencv-python
Author: Olli-Pekka Heinisuo
Author-email: UNKNOWN
License: MIT
```

**Comment by 6o6o** [comment]
Use
```
flow = cv2.calcOpticalFlowFarneback(img1, img2, None, 0.5, 3, 15, 3, 5, 1.2, 0)
```
Version 3.1 didn't seem to require this. Apparently they force initial `flow` argument before others now: https://github.com/opencv/opencv/issues/7276

**Comment by linrio** [comment]
OK. I have fixed it. thanks!

**Comment by linrio** [comment]
@6o6o How to use the `deepflow.cpp` in **opencv_contrib** ? In l [opencv_contrib](https://github.com/opencv/opencv_contrib/blob/master/modules/optflow/src/deepflow.cpp)

**Comment by 6o6o** [comment]
I haven't tried it. I'm not sure there are python bindings available.
